### ISSUE TITLE
Add support for Resilience4j Fallback

### ISSUE THREAD

**Issue by fabiocarvalho777** [paypal/mocca#11]
Although Mocca supports Resilience4j, support for Fallback was not added initially.
This issue is about adding that, besides also changing end user documentation accordingly (remove the statement below and add Fallback to the list of supported features).

> Notice Fallbacks are not supported at the moment.

Resilience4j has multiple builder setting methods for Fallback. All of them should be supported in Mocca Resilience4j builder.

**Comment by fabiocarvalho777** [comment]
Pasting below comments from original private repo.
[Here is the "this part" link.
](https://github.com/resilience4j/resilience4j/blob/81c758e177f954bf0f2580fa3ddd28f86a62a3d9/resilience4j-all/src/main/java/io/github/resilience4j/decorators/Decorators.java#L134)
![image](https://user-images.githubusercontent.com/5852907/125506784-82bcf131-b9ba-4cb1-8894-9c42a569a563.png)

**Comment by AmandeepSingh97** [comment]
@fabiocarvalho777 I think we can link the closed PR and close this issue.
