### ISSUE TITLE
Hosted javadoc (UI)

### ISSUE THREAD

**Issue by crankydillo** [paypal/mocca#3]
Some options:

- Github pages
- Any centralized javadoc website repository (search)
- Search for some website that will render nexus-contained -javadoc.jar files (may exist 🤷 )

**Comment by crankydillo** [comment]
[javadoc.io](https://javadoc.io) looks promising.  Hoping to knock this out soon.

**Comment by fabiocarvalho777** [comment]
Thanks Sam!!
