### ISSUE TITLE
JAXRS-based JagaHttpClient takes a JAXRS ClientBuilder, not Client..

### ISSUE THREAD

**Issue by crankydillo** [paypal/mocca#7]
this implies it has to build Clients, which it in fact does. It does this per request is likely a by-product of feign allowing timeouts at the request level. This is handled in different ways in the feign.Client impls..

Sorry for not providing code links, but I wanted to get this in before the day is done:)

**Comment by crankydillo** [comment]
Thought I wrote this down...

But one work-around (hack) is to take a `Client` instance and pass a `ClientBuilder` that will only ever return that one `Client` instance.

**Comment by crankydillo** [comment]
Given that we've found out multiple clients have issues with how the builder timeout work, I'm wondering if we should just hide that in our builder.  AFAIK, the main problem there is that there is no way to set timeouts on the default client.  I wonder if that's a big deal.  If it is, there are likely multiple ways we can address it.

Thoughts on removing those from the builder?

**Comment by fabiocarvalho777** [comment]
Hey Sam, just to make sure I understood, are you suggesting to remove the timeouts configuration from Mocca builder, and let users configure them directly with the HTTP clients (and then set the client in the builder)?

**Comment by crankydillo** [comment]
Yes, but I may do something to accommodate timeouts for the default client in the builder.  Of course, this would be a breaking API change.  I'll wait for opinion before coding it, but that's likely the route I would go.

**Comment by fabiocarvalho777** [comment]
That makes sense.

What if we just remove connection and request timeout from the builder, and if user wants to configure that for the default client, then they can configure the default client (like any other client) using `MoccaDefaultHttpClient`. In other words, we should move the connection and request timeout setters from the builder to class `MoccaDefaultHttpClient`.

What do you think?

**Comment by fabiocarvalho777** [comment]
By the way, we already do that for other properties in `MoccaDefaultHttpClient`. So I think that is the way to go.

**Comment by crankydillo** [comment]
I'm fine with that.  I will submit a PR before Monday.

**Comment by fabiocarvalho777** [comment]
Cool, thanks Sam!!
